name: housely
description: Production-grade offline-first Apartment Management Application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  riverpod_annotation:
  drift:
  sqlite3_flutter_libs:
  path_provider:
  path:
  go_router:
  uuid:
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  riverpod_generator:
  drift_dev:


flutter:
  uses-material-design: true